apiVersion: apps/v1
kind: Deployment
metadata:
  name: nledu-mysql
  namespace: jhub
spec:
  selector:
    matchLabels:
      app: nledu-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: nledu-mysql
    spec:
      containers:
      - name: nledu-mysql
        image: mysql:8.0.27
        imagePullPolicy: IfNotPresent
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "newlandedu"
        - name: TZ
          value: Asia/Shanghai
        securityContext:
          privileged: true
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: jhub-mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: jhub-mysql-pv
        #数据文件 权限需要修改 chmod -R +777 /home/data/mysql
        persistentVolumeClaim:
          claimName: jhub-mysql
