apiVersion: v1
kind: Service
metadata:
  name: jhub-mysql-svc
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 31307
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: my-mysql
    app.kubernetes.io/name: mysql
