apiVersion: apps/v1
kind: Deployment
metadata:
  name: teaching-server
  namespace: nledu
  labels:
    name: teaching-server
spec:
  selector:
    matchLabels:
      name: teaching-server 
  template:
    metadata:
      name: teaching-server
      labels:
        name: teaching-server
    spec:
      containers:
      - name: teaching-server
        image: imageserver:8080/nledu-cloud/nledu-cloud-teaching-server:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: appname
          value: nledu-cloud-teaching-server
        - name: appenv
          value: develop
        envFrom:
        - configMapRef:
            name: devmap
        ports:
        - name: teach
          containerPort: 9292
        - name: teaching
          containerPort: 29292
---
apiVersion: v1
kind: Service
metadata:
  name: teaching-server 
  namespace: nledu
  labels:
    name: teaching-server
spec:
  ports:
    - name: teach
      port: 9292
      targetPort: teach
    - name: teaching
      port: 29292
      targetPort: teaching
  selector:
    name: teaching-server
