---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-test1
  namespace: jhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-storage-class
